import type { Metadata } from "next";
import Navbar from "../_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InfoLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar isRoot={true} />
      <div className="background-image"></div>
      {children}
    </>
  );
}
